---
abstract: 'Plack middleware that records your client-server interactions'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  HTML::Tree: 0
  HTTP::Request::Common: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Recorder
requires:
  Carp: 0
  Getopt::Long: 0
  HTTP::Request: 0
  IO::File: 0
  IO::String: 0
  Plack: 0
  Plack::Client: 0
  Plack::Middleware::Debug: 0
  Pod::Usage: 0
  Storable: 0
  autodie: 0
  namespace::clean: 0
  perl: 5.8.8
resources:
  bugtracker: https://github.com/hoelzro/plack-middleware-recorder/issues
  homepage: https://github.com/hoelzro/plack-middleware-recorder
  repository: https://github.com/hoelzro/plack-middleware-recorder.git
version: 0.03
